build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related production2 APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}002919a3ceeb2b8cb1ab635de1630a30a55bb2dcee0e29d4697b3e60a30ef29703d5bf45c14a69c96c162c0cc731183b"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
